server:
  port: 9393
management:
  contextPath: /management
cloudfoundry:
  apiEndpoint: https://api.run.pez.pivotal.io
  organization: igopinathan
  space: development
  domain: cfapps.pez.pivotal.io
  services: ilaya-redis

security:
  basic:
    enabled: false
  oauth2:
    client:
      access-token-uri: https://login.run.pez.pivotal.io/oauth/token
      grantType: password
      client-id: cf
      password: pivotal
      user-authorization-uri: https://login.run.pez.pivotal.io/oauth/authorize
      username: igopinathan+pez@pivotal.io
    resource:
      userInfoUri: https://uaa.run.pez.pivotal.io/userinfo
spring:
  application:
    name: spring-cloud-data-admin
  cloud:
    config:
      uri: http://localhost:8888
#
# If you prefer to use Eureka to locate the Config Server, you can do that by setting
# spring.cloud.config.discovery.enabled=true (default "false"). The net result of that is 
# that client apps all need a bootstrap.yml (or an environment variable) with the Eureka 
# server address, e.g. in eureka.client.serviceUrl.defaultZone
#
#  cloud:
#     config:
#        discovery:
#           enabled: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/